name: Concurrent Run

on:
  workflow_dispatch:
    inputs:
      CHECK:
        description: 'Invoke Job' 
        type: string
        required: true
        
concurrency:
  #group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  group: 'test-concurrency'
  cancel-in-queue: false
  #cancel-in-progress: false

jobs:
  talisman_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Detect secrets with Talisman in incoming commits
        uses: carhartl/talisman-secrets-scan-action@v1.4.0
